spring:
  application:
    name: api-gateway
  cloud:
    gateway:
     discovery:
       enabled: true
server:
  port: ${PORT:8785}
  eureka:
    client:
    service-url:
      default-zone: ${EUREKA_URL:http://localhost:8761/eureka},
